CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Referendums (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL
);

CREATE TABLE Votes (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ReferendumId UNIQUEIDENTIFIER NOT NULL,
    VoteChoice BIT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (ReferendumId) REFERENCES Referendums(Id)
);

CREATE TABLE Eligibilities (
    UserId UNIQUEIDENTIFIER NOT NULL,
    ReferendumId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (UserId, ReferendumId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (ReferendumId) REFERENCES Referendums(Id)
);